apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 25
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
